//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.26 at 02:53:23 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://it.camp.pl/countries/")
package pl.camp.it.countries;
